
INCSDIR= /usr/include/aarch64

INCS= 	archconst.h archtypes.h bootarchive.h diskparm.h elf.h fpu.h interrupt.h \
	ipcconst.h memory.h multiboot.h partition.h \
	stackframe.h vm.h

.include <bsd.kinc.mk>
