/*
 * The Rockchip half: everything around the controller that no xHCI or
 * Synopsys document mentions, and without which the xHCI registers at the
 * same address mean nothing at all.
 *
 * Four things here cannot be worked out from the controller, and each was
 * read out of a working system before it was written (the recipe and the
 * numbers are in port/cb2-usb/registers.md):
 *
 *   - the power domain.  Both xHCIs of this SoC sit inside PD_PIPE, and a
 *     domain that is off is not "registers reading zero" but a bus that
 *     does not answer.
 *   - the 480 MHz clock USB 2.0 runs on is generated by the PHY, and the
 *     clock controller has to be told to look at the PHY rather than at
 *     the crystal.  One two-bit field in one register, reflected nowhere;
 *     with the crystal selected the controller comes up and sees nothing.
 *   - the PHY, which is two register files with similar offsets: the
 *     analogue part at the node's own address and the logical part in a
 *     separate syscon it points at.  Writing to the wrong one lands in a
 *     register that exists, so the mistake is silent.
 *   - the DWC3 wrapper, which must be put in host mode and have its HS
 *     PHY interface described to it before the xHCI underneath is touched.
 *
 * Every register of the clock controller and the PMU is hiword-masked: the
 * write says in its upper half which bits of its lower half it means.  So
 * none of that is read-modify-write and none of it can lose a neighbouring
 * field to whoever else writes the same register.  The PHY's two files are
 * not all of a kind - the filter registers there are plain 32-bit values,
 * and that is checked against the board rather than assumed.
 */

#include <minix/drivers.h>
#include <minix/syslib.h>
#include <sys/mman.h>

#include "xhci.h"
#include "xhcireg.h"

/*
 * The reset lines of this SoC that this driver names.  They are numbers in
 * the tree - "resets = <&cru SRST_USB3OTG0>" - and the driver has to know
 * which controller a line belongs to, because that is what decides which
 * of the two sets of clock gates to open.  Deriving it from the register
 * address instead would be the same fact stated less directly.
 */
#define RK3568_SRST_USB3OTG0	148
#define RK3568_SRST_USB3OTG1	149

/*
 * The power domains this driver can be asked about.  One line, because
 * one domain holds both USB3 controllers; the other domains of the SoC are
 * no business of a USB driver.  The bit numbers are from the vendor
 * kernel of the version running on the board.
 */
static const struct {
	int id;
	uint32_t pwr_mask;		/* in PWR_CON and PWR_STATUS */
	uint32_t idle_mask;		/* in IDLE_REQ, _ACK and _ST */
} domains[] = {
	{ 15, 1 << 8, 1 << 11 },	/* RK3568_PD_PIPE */
};

/*
 * What the working system has in the registers this driver writes.  Not a
 * table to copy blindly: the driver computes each value from what it is
 * trying to do, and then this says whether the result is what the board
 * runs with.  A DIFFERS line is not by itself an error - the vendor system
 * does more than a host-only bring-up needs - but every one of them is a
 * question worth asking, and that is what earned its keep on the GMAC.
 */
struct refreg {
	const char *name;
	unsigned block;			/* 0 ctrl, 1 usbgrf, 2 phy, 3 cru */
	unsigned off;
	uint32_t value;
	uint32_t mask;			/* the bits that are compared */
};

#define REF_CTRL	0
#define REF_USBGRF	1
#define REF_PHY		2
#define REF_CRU		3

static const struct refreg reference[] = {
	{ "GCTL",	 REF_CTRL,   DWC3_GCTL,		0x30c11004, ~0u },
	{ "GUSB2PHYCFG", REF_CTRL,   DWC3_GUSB2PHYCFG0,	0x00101408, ~0u },
	{ "GSNPSID",	 REF_CTRL,   DWC3_GSNPSID,	0x5533300a, ~0u },
	{ "otg con0",	 REF_USBGRF, RK_USBGRF_OTG_CON0, 0x00000c00, 0x000007ff },
	{ "con2",	 REF_USBGRF, RK_USBGRF_CON2,	0x00000000, 0x0000ffff },
	{ "ls filter",	 REF_USBGRF, RK_USBGRF_LS_FILTER_CON, 0x00030100,
	    0x000fffff },
	{ "bvalid filter", REF_USBGRF, RK_USBGRF_BVALID_FILTER, 0x000f4240,
	    0x000fffff },
	{ "id filter",	 REF_USBGRF, RK_USBGRF_ID_FILTER, 0x000f4240,
	    0x000fffff },
	{ "phy preemph", REF_PHY,    RK_PHY_REG_PREEMPHASIS, 0x00000004,
	    0x00000007 },
	{ "phy eye",	 REF_PHY,    RK_PHY_REG_EYE,	0x00000061, 0x000000ff },
	{ "mode con0",	 REF_CRU,    RK3568_CRU_MODE_CON0, 0x00004455,
	    0x0000c000 },
	{ "pipe gates",	 REF_CRU,    RK3568_CRU_CLKGATE_CON(
	    RK3568_CLKGATE_PIPE), 0x00000010, 0x00000703 },
};

int
xhci_rk_map(void)
{
	struct xhci_devinfo *in = &xhci.info;
	void *v;

	v = vm_map_phys(SELF, (void *)in->base, in->size);
	if (v == MAP_FAILED) {
		log_warn(&xhci_log, "cannot map the controller at 0x%lx; "
		    "not granted by RS?\n", (unsigned long)in->base);
		return EPERM;
	}
	xhci.regs = (vir_bytes)v;

	/*
	 * The blocks around it.  The clock controller and both halves of
	 * the PHY are refused rather than warned about: a driver that has
	 * the controller and not these can read its identity register and
	 * do nothing else.  The PMU and the PMU's clock controller are
	 * warnings, because a machine whose firmware already powered the
	 * domain and started the reference clock needs neither.
	 */
	if (in->cru_base == 0) {
		log_warn(&xhci_log, "the tree names no clock controller\n");
		return ENXIO;
	}
	if ((v = vm_map_phys(SELF, (void *)in->cru_base, in->cru_size)) ==
	    MAP_FAILED) {
		log_warn(&xhci_log, "cannot map the CRU at 0x%lx\n",
		    (unsigned long)in->cru_base);
		return EPERM;
	}
	xhci.cru = (vir_bytes)v;

	if ((v = vm_map_phys(SELF, (void *)in->phy_base, in->phy_size)) ==
	    MAP_FAILED) {
		log_warn(&xhci_log, "cannot map the PHY at 0x%lx\n",
		    (unsigned long)in->phy_base);
		return EPERM;
	}
	xhci.phy = (vir_bytes)v;

	if ((v = vm_map_phys(SELF, (void *)in->usbgrf_base, in->usbgrf_size))
	    == MAP_FAILED) {
		log_warn(&xhci_log, "cannot map the PHY's usbgrf at 0x%lx\n",
		    (unsigned long)in->usbgrf_base);
		return EPERM;
	}
	xhci.usbgrf = (vir_bytes)v;

	if (in->pmucru_base != 0) {
		v = vm_map_phys(SELF, (void *)in->pmucru_base,
		    in->pmucru_size);
		if (v == MAP_FAILED)
			log_warn(&xhci_log, "cannot map the PMU's clock "
			    "controller at 0x%lx; carrying on with whatever "
			    "reference clock the firmware left running\n",
			    (unsigned long)in->pmucru_base);
		else
			xhci.pmucru = (vir_bytes)v;
	}

	if (in->pmu_base != 0) {
		v = vm_map_phys(SELF, (void *)in->pmu_base, in->pmu_size);
		if (v == MAP_FAILED)
			log_warn(&xhci_log, "cannot map the PMU at 0x%lx; "
			    "the power domain will have to be however the "
			    "firmware left it\n",
			    (unsigned long)in->pmu_base);
		else
			xhci.pmu = (vir_bytes)v;
	}

	return OK;
}

/*
 * The power domain.
 *
 * Read first, and say what was read.  On this board the question is open
 * until a run answers it: the loader boots off eMMC and has no use for
 * PD_PIPE, so it may well arrive switched off, and it may equally well be
 * left on by the firmware before it.  Either way the sequence below is the
 * one the vendor kernel uses, and it is a no-op when the domain is already
 * on - which is the case worth having, because it means this code is not
 * on the path to a working controller until the day it is needed.
 */
int
xhci_rk_power_domain(void)
{
	unsigned i, spins;
	uint32_t pwr_mask = 0, idle_mask = 0;
	int id = xhci.info.power_domain;

	if (xhci.pmu == 0 || id < 0) {
		log_info(&xhci_log, "no power domain named for this "
		    "controller; assuming it is powered\n");
		return OK;
	}

	for (i = 0; i < sizeof(domains) / sizeof(domains[0]); i++)
		if (domains[i].id == id) {
			pwr_mask = domains[i].pwr_mask;
			idle_mask = domains[i].idle_mask;
		}

	if (pwr_mask == 0) {
		log_warn(&xhci_log, "power domain %d is not one this driver "
		    "knows the bits of; assuming it is powered\n", id);
		return OK;
	}

	if (!(xhci_rd(xhci.pmu, RK3568_PMU_PWR_STATUS) & pwr_mask)) {
		log_info(&xhci_log, "power domain %d is already on\n", id);
		return OK;
	}

	log_info(&xhci_log, "power domain %d is off; switching it on\n", id);

	/* Power up, then let the bus out of idle - in that order. */
	xhci_wr(xhci.pmu, RK3568_PMU_PWR_CON, (pwr_mask << 16));

	for (spins = 0; spins < 10000; spins++) {
		if (!(xhci_rd(xhci.pmu, RK3568_PMU_PWR_STATUS) & pwr_mask))
			break;
		micro_delay(10);
	}
	if (xhci_rd(xhci.pmu, RK3568_PMU_PWR_STATUS) & pwr_mask) {
		log_warn(&xhci_log, "power domain %d did not come up\n", id);
		return EIO;
	}

	xhci_wr(xhci.pmu, RK3568_PMU_IDLE_REQ, (idle_mask << 16));
	for (spins = 0; spins < 10000; spins++) {
		if (!(xhci_rd(xhci.pmu, RK3568_PMU_IDLE_ST) & idle_mask))
			break;
		micro_delay(10);
	}
	if (xhci_rd(xhci.pmu, RK3568_PMU_IDLE_ST) & idle_mask) {
		log_warn(&xhci_log, "power domain %d stayed idle\n", id);
		return EIO;
	}

	log_info(&xhci_log, "power domain %d is on\n", id);
	return OK;
}

/* Which of the two USB3 controllers this is, as the tree's reset line says. */
static int
controller_unit(void)
{
	unsigned i;

	for (i = 0; i < xhci.info.nresets; i++) {
		if (xhci.info.reset_id[i] == RK3568_SRST_USB3OTG0)
			return 0;
		if (xhci.info.reset_id[i] == RK3568_SRST_USB3OTG1)
			return 1;
	}

	/*
	 * No reset line this driver recognises.  The port of the PHY is the
	 * other thing the tree states, and on this SoC the OTG port serves
	 * the first controller; say which way the guess went rather than
	 * making it silently.
	 */
	log_warn(&xhci_log, "the tree names no reset line this driver knows; "
	    "taking this for controller %d from its PHY port\n",
	    xhci.info.phy_port);
	return xhci.info.phy_port == 0 ? 0 : 1;
}

/*
 * Let the clocks run.  A bit set in a gate register means the clock is
 * off, so switching one on is writing a zero under its mask.
 */
void
xhci_rk_clocks_on(void)
{
	uint32_t gates;
	int unit = controller_unit();

	/*
	 * The PHY's reference clock, which lives in the PMU's clock
	 * controller and not in the main one.
	 *
	 * Both candidate sources are ungated rather than one, and that is
	 * deliberate.  The board runs with the multiplexer reading 0 and
	 * with the source the vendor's own table calls 0 - clk_ref24m -
	 * gated off, while the PHY plainly works; so one of the two
	 * readings is wrong and the register cannot say which.  Ungating
	 * both puts 24 MHz on the PHY's input under either reading, costs
	 * one crystal tap, and leaves the multiplexer where the working
	 * system has it.
	 */
	if (xhci.pmucru != 0) {
		gates = RK3568_PMU_GATE_CLK_REF24M |
		    (xhci.info.phy_unit == 0 ? RK3568_PMU_GATE_XIN_USBPHY0 :
		    RK3568_PMU_GATE_XIN_USBPHY1);
		xhci_wr(xhci.pmucru,
		    RK3568_PMUCRU_CLKGATE_CON(RK3568_PMU_CLKGATE_USB),
		    gates << 16);
	}

	/* The controller's own clocks, and the bus they hang off. */
	gates = RK3568_GATE_ACLK_PIPE | RK3568_GATE_PCLK_PIPE;
	if (unit == 0)
		gates |= RK3568_GATE_ACLK_USB3OTG0 |
		    RK3568_GATE_CLK_USB3OTG0_REF |
		    RK3568_GATE_CLK_USB3OTG0_SUSPEND;
	else
		gates |= RK3568_GATE_ACLK_USB3OTG1 |
		    RK3568_GATE_CLK_USB3OTG1_REF |
		    RK3568_GATE_CLK_USB3OTG1_SUSPEND;

	xhci_wr(xhci.cru, RK3568_CRU_CLKGATE_CON(RK3568_CLKGATE_PIPE),
	    gates << 16);

	/* The suspend clock comes from the crystal, as on the board. */
	xhci_wr(xhci.cru, RK3568_CRU_CLKSEL_CON(RK3568_CLKSEL_PIPE),
	    rk_hiword(0, 1, unit == 0 ? RK3568_USB3OTG0_SUSPEND_SRC_BIT :
	    RK3568_USB3OTG1_SUSPEND_SRC_BIT));

	/*
	 * And the one write that nothing reflects: where the 480 MHz clock
	 * of USB 2.0 comes from.  It is generated by the PHY, and this is
	 * the tree's "assigned-clocks = <&cru USB480M>" with the PHY as its
	 * parent - a statement about the board's wiring that no register of
	 * the controller can be asked about.
	 */
	xhci_wr(xhci.cru, RK3568_CRU_MODE_CON0,
	    rk_hiword(RK3568_MODE_USB480M_PHY, RK3568_MODE_USB480M_MASK,
	    RK3568_MODE_USB480M_SHIFT));

	log_debug(&xhci_log, "clocks on for controller %d, phy %d\n", unit,
	    xhci.info.phy_unit);
}

/* Pulse the reset lines the tree named for this controller. */
static void
reset_controller(void)
{
	unsigned i, id, reg, bit;

	for (i = 0; i < xhci.info.nresets; i++) {
		id = xhci.info.reset_id[i];
		reg = RK3568_CRU_SOFTRST_CON(id / RK_SOFTRST_PER_REG);
		bit = id % RK_SOFTRST_PER_REG;
		xhci_wr(xhci.cru, reg, rk_hiword(1, 1, bit));
	}

	micro_delay(100);

	for (i = 0; i < xhci.info.nresets; i++) {
		id = xhci.info.reset_id[i];
		reg = RK3568_CRU_SOFTRST_CON(id / RK_SOFTRST_PER_REG);
		bit = id % RK_SOFTRST_PER_REG;
		xhci_wr(xhci.cru, reg, rk_hiword(0, 1, bit));
	}

	/* The core needs its clocks to settle before it is spoken to. */
	micro_delay(1000);
}

/*
 * The PHY.
 *
 * Two register files, and the split is not cosmetic: the logical fields
 * are in the syscon the PHY node points at, the analogue tuning is at the
 * node's own address.  What is written here is what the working system has
 * in these registers, and nothing else - in particular the line-state
 * detectors are left alone, because on this port it is the xHCI that
 * notices a device arriving, and the PHY's detector exists for waking a
 * suspended controller, which a host-only bring-up never does.
 *
 * The one field that has to be written is phy_sus: nine bits saying the
 * port is not suspended.  The bits above it in the same register belong to
 * the role signalling, whose value on the board this driver does not
 * pretend to understand - so it does not touch them, and reports them
 * instead.
 */
void
xhci_rk_phy_init(void)
{
	unsigned port_off = xhci.info.phy_port == 0 ? RK_USBGRF_OTG_CON0 :
	    RK_USBGRF_HOST_CON0;
	unsigned analog = xhci.info.phy_port == 0 ? 0 : RK_PHY_PORT_STRIDE;
	uint32_t sus = xhci.info.phy_port == 0 ? RK_PHY_SUS_ON :
	    RK_PHY_SUS_CTRL;

	/* The 480 MHz output, which is what the CRU was just pointed at. */
	xhci_wr(xhci.usbgrf, RK_USBGRF_CON2,
	    rk_hiword(0, 1, RK_USBGRF_CLKOUT_CTL_BIT));

	/* The port runs. */
	xhci_wr(xhci.usbgrf, port_off, rk_hiword(sus, RK_PHY_SUS_MASK, 0));

	/*
	 * The filters, which are plain 32-bit registers here and not
	 * hiword-masked - twenty bits of counter would not fit under a
	 * mask in the top half, and the board reads back the bare value.
	 * That is the sort of thing that is checked rather than assumed;
	 * see port/cb2-usb/registers.md.
	 */
	xhci_wr(xhci.usbgrf, RK_USBGRF_LS_FILTER_CON, RK_LS_FILTER_VALUE);
	if (xhci.info.phy_unit == 0) {
		xhci_wr(xhci.usbgrf, RK_USBGRF_BVALID_FILTER,
		    RK_FILTER_COUNTER);
		xhci_wr(xhci.usbgrf, RK_USBGRF_ID_FILTER, RK_FILTER_COUNTER);
	}

	/*
	 * The analogue tuning, which is in no specification and which the
	 * vendor driver does for this part: pre-emphasis outside the chirp
	 * phase on each port, the differential receiver off to save power,
	 * and on this PHY a taller high-speed eye - 437.5 mV where the
	 * default is 400.
	 */
	xhci_wr(xhci.phy, analog + RK_PHY_REG_PREEMPHASIS,
	    (xhci_rd(xhci.phy, analog + RK_PHY_REG_PREEMPHASIS) & ~0x7u) |
	    RK_PHY_PREEMPHASIS_VAL);

	if (xhci.info.phy_base == RK3568_USB2PHY0_BASE) {
		uint32_t v = xhci_rd(xhci.phy, analog + RK_PHY_REG_EYE);

		v &= ~(RK_PHY_EYE_DIFFRCV_BIT |
		    (RK_PHY_EYE_HEIGHT_MASK << RK_PHY_EYE_HEIGHT_SHIFT));
		v |= RK_PHY_EYE_HEIGHT_437MV << RK_PHY_EYE_HEIGHT_SHIFT;
		xhci_wr(xhci.phy, analog + RK_PHY_REG_EYE, v);
	}

	/* The PHY needs a moment before the core is told to look at it. */
	micro_delay(2000);
}

/*
 * The DWC3 wrapper, and only then the xHCI.
 *
 * Host-only, which shortens this considerably: the device side's own soft
 * reset is for the gadget half, and the vendor driver skips it in host
 * mode on the grounds that the xHCI driver resets the host block itself -
 * which is what xhci.c does with USBCMD.HCRST.  What is left is the mode
 * change, which the core requires be made with its soft reset held, and
 * the description of the HS PHY interface.
 */
int
xhci_rk_dwc3_init(void)
{
	uint32_t reg, id;
	unsigned spins;

	reset_controller();

	id = xhci_rd(xhci.regs, DWC3_GSNPSID);
	xhci.dwc3_id = id;

	if ((id & DWC3_GSNPSID_MASK) != DWC3_GSNPSID_DWC3) {
		log_warn(&xhci_log, "no DWC3 core answers at 0x%lx: "
		    "GSNPSID 0x%08x\n", (unsigned long)xhci.info.base, id);
		return ENXIO;
	}

	log_info(&xhci_log, "dwc3 core %x.%02x (GSNPSID 0x%08x)\n",
	    (id >> 12) & 0xf, id & 0xfff, id);

	/*
	 * Hold the core in soft reset for the mode change.  The
	 * documentation asks for 100 ms before it is let go, and this is
	 * one of those waits that only shows up as an intermittent failure
	 * if it is shortened.
	 */
	reg = xhci_rd(xhci.regs, DWC3_GCTL);
	reg |= DWC3_GCTL_CORESOFTRESET;
	xhci_wr(xhci.regs, DWC3_GCTL, reg);

	micro_delay(100000);

	reg = xhci_rd(xhci.regs, DWC3_GCTL);
	reg &= ~DWC3_GCTL_CORESOFTRESET;
	reg &= ~(DWC3_GCTL_PRTCAPDIR_MASK << DWC3_GCTL_PRTCAPDIR_SHIFT);
	reg |= DWC3_GCTL_PRTCAPDIR_HOST << DWC3_GCTL_PRTCAPDIR_SHIFT;
	reg &= ~DWC3_GCTL_SCALEDOWN_MASK;
	reg &= ~DWC3_GCTL_DISSCRAMBLE;
	xhci_wr(xhci.regs, DWC3_GCTL, reg);

	/*
	 * The HS PHY interface: sixteen bits wide, which the tree says as
	 * phy_type = "utmi_wide", and a turnaround time that goes with the
	 * width.  Then the two suspend-related bits the board's quirk list
	 * asks to be clear - the core may set them again once it is up, and
	 * on the other controller of this SoC the vendor system does.
	 */
	reg = xhci_rd(xhci.regs, DWC3_GUSB2PHYCFG0);
	reg |= DWC3_GUSB2PHYCFG_PHYIF;
	reg &= ~(0xfu << 10);
	reg |= 5 << 10;				/* USBTRDTIM for 16 bits */
	reg &= ~DWC3_GUSB2PHYCFG_SUSPHY;
	reg &= ~DWC3_GUSB2PHYCFG_ENBLSLPM;
	reg &= ~DWC3_GUSB2PHYCFG_U2FREECLK_EXISTS;
	xhci_wr(xhci.regs, DWC3_GUSB2PHYCFG0, reg);

	/* And wait for the core to say it is out of reset. */
	for (spins = 0; spins < 1000; spins++) {
		if (!(xhci_rd(xhci.regs, DWC3_GCTL) & DWC3_GCTL_CORESOFTRESET))
			break;
		micro_delay(100);
	}

	log_info(&xhci_log, "dwc3 in host mode: GCTL 0x%08x, "
	    "GUSB2PHYCFG 0x%08x, GSTS 0x%08x\n",
	    xhci_rd(xhci.regs, DWC3_GCTL),
	    xhci_rd(xhci.regs, DWC3_GUSB2PHYCFG0),
	    xhci_rd(xhci.regs, DWC3_GSTS));

	return OK;
}

/*
 * What this driver made of the glue, against what the board runs with.
 *
 * The value of this is not that the numbers match - the vendor system does
 * more than a host-only bring-up needs, so some of them will not - but
 * that a difference is named out loud instead of being discovered three
 * milestones later as "the port sees nothing".  It is the same instrument
 * that found the PHY settings on the GMAC, and it costs one table.
 */
void
xhci_rk_report(void)
{
	unsigned i;
	vir_bytes block;
	uint32_t got;
	const char *unknown = NULL;

	log_info(&xhci_log, "glue registers, this driver against the board "
	    "(port/cb2-usb/registers.md):\n");

	for (i = 0; i < sizeof(reference) / sizeof(reference[0]); i++) {
		const struct refreg *r = &reference[i];

		switch (r->block) {
		case REF_CTRL:	 block = xhci.regs;	break;
		case REF_USBGRF: block = xhci.usbgrf;	break;
		case REF_PHY:	 block = xhci.phy;	break;
		case REF_CRU:	 block = xhci.cru;	break;
		default:	 block = 0;		break;
		}
		if (block == 0)
			continue;

		got = xhci_rd(block, r->off);
		log_info(&xhci_log, "  %-16s 0x%08x (reference 0x%08x)%s\n",
		    r->name, got, r->value,
		    ((got ^ r->value) & r->mask) != 0 ? "  DIFFERS" : "");
	}

	if (xhci.pmu != 0)
		log_info(&xhci_log, "  %-16s 0x%08x (pd status; bit 8 set "
		    "means PD_PIPE is off)\n", "pmu status",
		    xhci_rd(xhci.pmu, RK3568_PMU_PWR_STATUS));

	log_info(&xhci_log, "  %-16s 0x%08x (role bits above phy_sus; this "
	    "driver does not write them)\n", "phy role",
	    xhci_rd(xhci.usbgrf, RK_USBGRF_OTG_CON0) & ~RK_PHY_SUS_MASK);

	(void)unknown;
}
