#!/usr/bin/env python3
# Survey the MINIX message payload variants under ILP32 and LP64.
#
# Every variant in <minix/ipc.h> is pinned to 56 bytes by _ASSERT_MSG_SIZE.
# On LP64 pointers and the long-family types widen, so some variants no longer
# fit.  This script extracts the typedefs, compiles them for both AArch64 ABIs
# and reports what overflows, by how much, and which field is responsible.
#
# The MINIX types the payloads use are declared here rather than pulled from
# the tree: <minix/ipc.h> cannot be preprocessed for aarch64 until stage 1
# lands the machine headers.  The widths follow sys/sys/types.h, sys/sys/ansi.h
# and minix/include/minix/type.h; the ILP32 column reproduces the tree's own
# assertion (all 56), which is what validates them.
#
# Usage: python3 msgsize-survey.py [path/to/ipc.h]

import json
import os
import re
import subprocess
import sys
from collections import Counter

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 "../../../../include/minix/ipc.h")
OUT = "/tmp/msgprobe"
CC = "aarch64-linux-gnu-gcc"
OBJCOPY = "aarch64-linux-gnu-objcopy"

os.makedirs(OUT, exist_ok=True)
text = open(SRC).read()

# ---------------------------------------------------------------- extraction
start = text.index("typedef struct {\n\tuint8_t data[56];")
end = text.index("} mess_vmmcp_reply;")
end = text.index("\n", end) + 1
body = text[start:end]

blocks = re.findall(r"typedef struct \{\n(.*?)\n\} (mess_[A-Za-z0-9_]+);",
                    body, re.S)
names = [n for _, n in blocks]

# ------------------------------------------------------------- field parsing
# (size, alignment); "L" means "one machine long", i.e. it follows the ABI.
T = {
    "char": (1, 1), "signed char": (1, 1), "unsigned char": (1, 1),
    "short": (2, 2), "unsigned short": (2, 2),
    "int": (4, 4), "unsigned int": (4, 4), "unsigned": (4, 4),
    "long": ("L", "L"), "unsigned long": ("L", "L"),
    "long int": ("L", "L"), "unsigned long int": ("L", "L"),
    "long unsigned int": ("L", "L"),
    "int8_t": (1, 1), "uint8_t": (1, 1), "u8_t": (1, 1),
    "int16_t": (2, 2), "uint16_t": (2, 2), "u16_t": (2, 2),
    "int32_t": (4, 4), "uint32_t": (4, 4), "u32_t": (4, 4),
    "int64_t": (8, 8), "uint64_t": (8, 8), "u64_t": (8, 8),
    "endpoint_t": (4, 4), "cp_grant_id_t": (4, 4),
    "devmajor_t": (4, 4), "devminor_t": (4, 4),
    "clockid_t": (4, 4), "clock_t": (4, 4),
    "pid_t": (4, 4), "uid_t": (4, 4), "gid_t": (4, 4), "mode_t": (4, 4),
    "dev_t": (8, 8), "ino_t": (8, 8), "off_t": (8, 8), "time_t": (8, 8),
    "size_t": ("L", "L"), "ssize_t": ("L", "L"), "key_t": ("L", "L"),
    "vir_bytes": ("L", "L"), "phys_bytes": ("L", "L"),
    "sigset_t": (16, 4), "fd_set": (32, 4),
    "union ds_val": (4, 4),
}
LONGW = {"ilp32": 4, "lp64": 8}
GROWS = {"long", "unsigned long", "long int", "unsigned long int",
         "long unsigned int", "size_t", "ssize_t", "key_t",
         "vir_bytes", "phys_bytes"}
CONST = {"M_PATH_STRING_MAX": 40, "CTL_SHORTNAME": 8, "NR_DOMAIN": 8,
         "NDEV_NAME_MAX": 16, "NDEV_HWADDR_MAX": 6, "NDEV_IOV_MAX": 8}


def parse(fieldtext):
    """Return [(type, name, nelem, is_pointer)] for one struct body."""
    s = re.sub(r"/\*.*?\*/", " ", fieldtext, flags=re.S)
    out = []
    for decl in s.split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        m = re.match(r"^((?:const\s+)?(?:union\s+|struct\s+)?"
                     r"[A-Za-z_][A-Za-z0-9_]*"
                     r"(?:\s+(?:int|long|char|short))*)\s+(.*)$", decl)
        if not m:
            sys.exit("cannot parse declaration: %r" % decl)
        tname, rest = m.group(1), m.group(2)
        tname = re.sub(r"^const\s+", "", tname).strip()
        if tname == "void":
            tname = "char"		# only ever appears as void *
        for d in rest.split(","):
            d = d.strip()
            ptr = d.startswith("*")
            d = d.lstrip("* ")
            am = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\[([A-Za-z0-9_]+)\]$", d)
            if am:
                n = am.group(2)
                out.append((tname, am.group(1),
                            int(n) if n.isdigit() else CONST[n], ptr))
            else:
                out.append((tname, d, 1, ptr))
    return out


def layout(fields, abi):
    """Lay a parsed struct out by the C rules; return (size, [(name, off, sz)])."""
    off, maxa, detail = 0, 1, []
    for tname, name, n, ptr in fields:
        if ptr:
            sz = al = LONGW[abi]
        else:
            sz, al = T[tname]
            if sz == "L":
                sz = al = LONGW[abi]
        off = (off + al - 1) // al * al
        detail.append((name, off, sz * n))
        off += sz * n
        maxa = max(maxa, al)
    return (off + maxa - 1) // maxa * maxa, detail


# ------------------------------------------------------------- the C probe
PRELUDE = r"""
/* generated by msgsize-survey.py -- do not edit */
#include <stdint.h>
#define _ASSERT_MSG_SIZE(t) extern int _msgsz_unused_##t
#define M_PATH_STRING_MAX 40
#define CTL_SHORTNAME 8
#define NR_DOMAIN 8
#define NDEV_NAME_MAX 16
#define NDEV_HWADDR_MAX 6
#define NDEV_IOV_MAX 8
typedef int endpoint_t;
typedef int32_t cp_grant_id_t;
typedef unsigned long vir_bytes;
typedef unsigned long phys_bytes;
typedef uint8_t u8_t;
typedef uint16_t u16_t;
typedef uint32_t u32_t;
typedef uint64_t u64_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef int64_t off_t;
typedef int64_t time_t;
typedef unsigned int clock_t;
typedef int clockid_t;
typedef uint64_t dev_t;
typedef uint64_t ino_t;
typedef uint32_t mode_t;
typedef uint32_t uid_t;
typedef uint32_t gid_t;
typedef int32_t pid_t;
typedef long key_t;
typedef int32_t devmajor_t;
typedef int32_t devminor_t;
typedef struct { uint32_t __bits[4]; } sigset_t;
typedef struct { uint32_t fds_bits[8]; } fd_set;
"""

probe = PRELUDE + body
probe += "\nconst uint32_t probe[] __attribute__((section(\".probe\"), used)) = {\n"
probe += ",\n".join("\tsizeof(%s)" % n for n in names)
probe += "\n};\n"
open(OUT + "/probe.c", "w").write(probe)


def sizes(abi):
    """Compile the probe for one ABI and read the sizes back out of .probe.

    There is no aarch64 libc here and no user-mode emulator, so the answer is
    carried in an object-file section rather than printed by a running program.
    """
    flags = ["-mabi=ilp32"] if abi == "ilp32" else []
    obj = "%s/probe-%s.o" % (OUT, abi)
    raw = "%s/probe-%s.bin" % (OUT, abi)
    subprocess.run([CC, "-c", "-O2", "-ffreestanding", "-Wall"] + flags +
                   [OUT + "/probe.c", "-o", obj], check=True)
    subprocess.run([OBJCOPY, "-O", "binary", "-j", ".probe", obj, raw],
                   check=True)
    d = open(raw, "rb").read()
    return [int.from_bytes(d[i:i + 4], "little") for i in range(0, len(d), 4)]


s32, s64 = sizes("ilp32"), sizes("lp64")
assert len(s32) == len(s64) == len(names)

parsed = {}
bad = 0
for (fieldtext, name), a, b in zip(blocks, s32, s64):
    f = parse(fieldtext)
    parsed[name] = f
    c32 = layout(f, "ilp32")[0]
    c64 = layout(f, "lp64")[0]
    if (c32, c64) != (a, b):
        print("MISMATCH %-40s compiler %d/%d parser %d/%d" % (name, a, b, c32, c64))
        bad += 1

print("variants: %d   parser/compiler mismatches: %d" % (len(names), bad))
print("ILP32 all 56 bytes: %s (min %d, max %d)"
      % (all(x == 56 for x in s32), min(s32), max(s32)))

over = [(n, b) for n, b in zip(names, s64) if b > 56]
print("\nLP64: %d of %d variants overflow" % (len(over), len(names)))
hist = Counter(b for _, b in over)
for size in sorted(hist):
    print("   %3d bytes: %3d variants" % (size, hist[size]))
print("   fits in 64: %d   needs more than 64: %d"
      % (sum(1 for _, b in over if b <= 64), sum(1 for _, b in over if b > 64)))
print("   largest: %s" % ", ".join("%s=%d" % (n, b)
                                   for n, b in sorted(over, key=lambda x: -x[1])[:5]))


def culprits(f):
    c = Counter()
    for tname, name, n, ptr in f:
        if ptr:
            c["pointer"] += n
        elif tname in GROWS:
            c[tname] += n
    return c


tot, onlyptr, onlylong, both = Counter(), 0, 0, 0
for n, _ in over:
    c = culprits(parsed[n])
    tot += c
    p = c.get("pointer", 0)
    l = sum(v for k, v in c.items() if k != "pointer")
    if p and l:
        both += 1
    elif p:
        onlyptr += 1
    else:
        onlylong += 1
print("\noverflowing by cause: pointers only %d, long-family only %d, both %d"
      % (onlyptr, onlylong, both))
for k, v in tot.most_common():
    print("   %-16s %d" % (k, v))

allc, withptr = Counter(), 0
for n in names:
    c = culprits(parsed[n])
    if c.get("pointer"):
        withptr += 1
    allc += c
print("\nvariants with at least one pointer: %d" % withptr)
for k, v in allc.most_common():
    print("   %-16s %d" % (k, v))

# --------------------------------------------------------------------------
# How much of a variant is real content?  Every variant is padded out to 56
# with an explicit `padding[]` array, so overflow alone does not say whether a
# variant can be made to fit again.  Drop the padding and lay the rest out:
# that is the smallest the variant can be without touching its fields, i.e.
# without a re-cut that changes the meaning of the message.
def content(f, abi):
    return layout([x for x in f if x[1] != "padding"], abi)[0]


cont = {n: content(parsed[n], "lp64") for n in names}
nopad = [n for n in names if not any(x[1] == "padding" for x in parsed[n])]
print("\nvariants with no padding left at all: %d" % len(nopad))
for cap in (56, 64, 128):
    fit = sum(1 for n in names if cont[n] <= cap)
    print("   content fits in %3d bytes: %3d of %d variants" % (cap, fit, len(names)))
hard = sorted(((cont[n], n) for n in names if cont[n] > 56), reverse=True)
print("   over 56 after dropping padding: %d, largest:" % len(hard))
for c, n in hard[:8]:
    print("      %-40s %d" % (n, c))
print("   content-size histogram over 56:")
for size, cnt in sorted(Counter(c for c, _ in hard).items()):
    print("      %3d bytes: %3d" % (size, cnt))

json.dump({"names": names, "ilp32": s32, "lp64": s64,
           "content64": cont,
           "fields": {n: parsed[n] for n in names}},
          open(OUT + "/survey.json", "w"), indent=1)
print("\nwrote %s/survey.json" % OUT)
