#!/usr/bin/env python3
# Survey the MINIX message payload variants under ILP32 and LP64.
#
# Every variant in <minix/ipc.h> was pinned to 56 bytes by _ASSERT_MSG_SIZE.
# On LP64 pointers and the long-family types widen, so some variants no longer
# fit.  This script compiles all 256 for both AArch64 ABIs and reports what
# overflows, by how much, and which field is responsible.  It is what the size
# decision of stage 3 was made on; see port/PORTING-LOG.md.
#
# It reads the header, it does not write it: the padding[] arrays that follow
# from that decision are regenerated by gen-msgpadding.py.  Extraction, the
# type table and the layout rules are shared with that tool in msgpayload.py.
#
# Usage: python3 msgsize-survey.py [--cap N] [path/to/ipc.h]
#        --cap is the payload size everything is measured against; it defaults
#        to M_PAYLOAD_SIZE from <minix/ipcconst.h>.  To reproduce the survey
#        the decision was made on, take the header from before the decision
#        and measure it against the payload of the time:
#           git show 759435f:minix/include/minix/ipc.h > /tmp/ipc.h
#           python3 msgsize-survey.py --cap 56 /tmp/ipc.h

import json
import sys
from collections import Counter

import msgpayload as mp

argv = sys.argv[1:]
CAP = None
if "--cap" in argv:
    i = argv.index("--cap")
    CAP = int(argv[i + 1])
    del argv[i:i + 2]
SRC = argv[0] if argv else mp.DEFAULT_SRC
OUT = mp.DEFAULT_OUT
if CAP is None:
    CAP = mp.payload_size(mp.DEFAULT_SRC)

_, _, body, blocks, names = mp.extract(mp.read_source(SRC))

sizes = mp.compile_sizes(body, names, OUT)
s32, s64 = sizes["ilp32"], sizes["lp64"]
assert len(s32) == len(s64) == len(names)

parsed = {}
bad = 0
for (fieldtext, name), a, b in zip(blocks, s32, s64):
    f = mp.parse(fieldtext)
    parsed[name] = f
    c32 = mp.layout(f, "ilp32")[0]
    c64 = mp.layout(f, "lp64")[0]
    if (c32, c64) != (a, b):
        print("MISMATCH %-40s compiler %d/%d parser %d/%d" % (name, a, b, c32, c64))
        bad += 1

print("variants: %d   parser/compiler mismatches: %d   payload %d bytes"
      % (len(names), bad, CAP))
print("ILP32 all %d bytes: %s (min %d, max %d)"
      % (CAP, all(x == CAP for x in s32), min(s32), max(s32)))

over = [(n, b) for n, b in zip(names, s64) if b > CAP]
print("\nLP64: %d of %d variants overflow" % (len(over), len(names)))
hist = Counter(b for _, b in over)
for size in sorted(hist):
    print("   %3d bytes: %3d variants" % (size, hist[size]))
print("   fits in %d: %d   needs more: %d"
      % (CAP + 8, sum(1 for _, b in over if b <= CAP + 8),
         sum(1 for _, b in over if b > CAP + 8)))
print("   largest: %s" % ", ".join("%s=%d" % (n, b)
                                   for n, b in sorted(over, key=lambda x: -x[1])[:5]))


def culprits(f):
    c = Counter()
    for tname, name, n, ptr in f:
        if ptr:
            c["pointer"] += n
        elif tname in mp.GROWS:
            c[tname] += n
    return c


tot, onlyptr, onlylong, both = Counter(), 0, 0, 0
for n, _ in over:
    c = culprits(parsed[n])
    tot += c
    p = c.get("pointer", 0)
    l = sum(v for k, v in c.items() if k != "pointer")
    if p and l:
        both += 1
    elif p:
        onlyptr += 1
    else:
        onlylong += 1
print("\noverflowing by cause: pointers only %d, long-family only %d, both %d"
      % (onlyptr, onlylong, both))
for k, v in tot.most_common():
    print("   %-16s %d" % (k, v))

allc, withptr = Counter(), 0
for n in names:
    c = culprits(parsed[n])
    if c.get("pointer"):
        withptr += 1
    allc += c
print("\nvariants with at least one pointer: %d" % withptr)
for k, v in allc.most_common():
    print("   %-16s %d" % (k, v))

# --------------------------------------------------------------------------
# How much of a variant is real content?  Every variant is padded out to the
# payload size with an explicit `padding[]` array, so overflow alone does not
# say whether a variant can be made to fit again.  Drop the padding and lay
# the rest out: that is the smallest the variant can be without touching its
# fields, i.e. without a re-cut that changes the meaning of the message.
cont = {n: mp.content(parsed[n], "lp64") for n in names}
nopad = [n for n in names if not any(x[1] == mp.PAD for x in parsed[n])]
print("\nvariants with no padding left at all: %d" % len(nopad))
for cap in sorted({56, 64, CAP, 128}):
    fit = sum(1 for n in names if cont[n] <= cap)
    print("   content fits in %3d bytes: %3d of %d variants" % (cap, fit, len(names)))
hard = sorted(((cont[n], n) for n in names if cont[n] > CAP), reverse=True)
print("   over %d after dropping padding: %d, largest:" % (CAP, len(hard)))
for c, n in hard[:8]:
    print("      %-40s %d" % (n, c))
print("   content-size histogram over the payload:")
for size, cnt in sorted(Counter(c for c, _ in hard).items()):
    print("      %3d bytes: %3d" % (size, cnt))

json.dump({"names": names, "ilp32": s32, "lp64": s64,
           "content64": cont,
           "fields": {n: parsed[n] for n in names}},
          open(OUT + "/survey.json", "w"), indent=1)
print("\nwrote %s/survey.json" % OUT)
